[project]
name = "diplom-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "django-jazzmin>=3.0.1",
    "numpy>=2.3.5",
    "psycopg2-binary>=2.9.11",
    "python-dateutil>=2.9.0.post0",
]
