name: warehouse_erp

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warehouse"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data

  manage:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django_manage
    volumes:
      - ../src:/app/src
    working_dir: /app/src/backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    entrypoint: ["uv", "run", "manage.py"]
    command: ["migrate"]

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      manage:
        condition: service_completed_successfully
    restart: always
    volumes:
      - ../src:/app/src
    working_dir: /app/src/backend
    ports:
      - "8000:8000"
    command: uv run uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --lifespan off

  worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django_worker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      manage:
        condition: service_completed_successfully
    volumes:
      - ../src:/app/src
    working_dir: /app/src/backend
    command: uv run manage.py rqworker default

volumes:
  pgdata:
  redisdata:
