name: warehouse_crm

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - ../src:/app/src
    working_dir: /app/src/backend
    ports:
      - "8000:8000"
    # command: uv run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    command: uv run manage.py runserver 0.0.0.0:8000

  worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: django_worker
    depends_on:
      - db
      - redis
    volumes:
      - ../src:/app/src
    working_dir: /app/src/backend
    command: uv run manage.py rqworker default

volumes:
  pgdata:
  redisdata: # Новий том для збереження даних Redis
